# Generated by Django 3.0.7 on 2020-06-23 14:21
from django.db import migrations, models

from drf_integrations.utils import package_semver


def can_migrate():
    return package_semver("django-oauth-toolkit") >= (1, 3)


def get_oauth_dependencies():
    # Ignore versions before squashed migrations (< 1.3)
    if can_migrate():
        return [("oauth2_provider", "0002_auto_20190406_1805")]
    return []


class Migration(migrations.Migration):

    dependencies = [("drf_integrations", "0001_initial")] + get_oauth_dependencies()

    operations = (
        [
            migrations.AddField(
                model_name="grant",
                name="code_challenge",
                field=models.CharField(blank=True, default="", max_length=128),
            ),
            migrations.AddField(
                model_name="grant",
                name="code_challenge_method",
                field=models.CharField(
                    blank=True,
                    choices=[("plain", "plain"), ("S256", "S256")],
                    default="",
                    max_length=10,
                ),
            ),
        ]
        if can_migrate()
        else []
    )
