# Generated by Django 3.0.7 on 2020-06-23 14:21
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drf_integrations", "0001_initial"),
        ("oauth2_provider", "0002_auto_20190406_1805"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="code_challenge",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="grant",
            name="code_challenge_method",
            field=models.CharField(
                blank=True,
                choices=[("plain", "plain"), ("S256", "S256")],
                default="",
                max_length=10,
            ),
        ),
    ]
