# Generated by Django 3.1.5 on 2021-01-18 13:17

from django.db import migrations

from drf_integrations.fields import get_json_field

JSONField = get_json_field()


class Migration(migrations.Migration):

    dependencies = [
        ("drf_integrations", "0002_auto_20200623_1421"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationinstallation",
            name="config",
            field=JSONField(blank=True, null=True),
        ),
    ]
