# Generated by Django 3.1.5 on 2021-01-18 13:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drf_integrations", "0002_auto_20200623_1421"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationinstallation",
            name="config",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
