# Generated by Django 3.2.13 on 2022-05-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drf_integrations", "0004_auto_20220503_1428"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationinstallation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
