# Generated by Django 3.2.19 on 2023-06-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drf_integrations", "0005_alter_applicationinstallation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grant",
            name="redirect_uri",
            field=models.TextField(),
        ),
    ]
