# Generated by Django 3.2.13 on 2023-04-03 07:39
"""
This migration conditionally switches between the Grant.redirect_uri CharField or TextField
which changes based on django-oauth-toolkit version.
"""
from django.db import migrations, models
from oauth2_provider.models import AbstractGrant

is_text_field = isinstance(AbstractGrant.redirect_uri, models.TextField)


class Migration(migrations.Migration):

    dependencies = [
        ("drf_integrations", "0005_alter_applicationinstallation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grant",
            name="redirect_uri",
            field=models.TextField() if is_text_field else models.CharField(max_length=255),
        ),
    ]
