repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
    -   id: ruff
        alias: autoformat
        args: [--fix]
    -   id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
        language_version: python3.12
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
        language_version: python3.12
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: no-commit-to-branch
        args: [--branch=master]
      - id: trailing-whitespace

  # Add the local repository for custom hooks
  - repo: local
    hooks:
      - id: django-check
        name: Run 'django check'
        entry: pre_commit_hooks/django_check.sh
        language: system
        pass_filenames: false
