version: '2'

services:

  postgres:
    image: postgres:15
    container_name: drfintegrations-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata15:/var/lib/postgresql/data

volumes:
  pgdata15:
    external: true
