[tox]
isolated_build = True
envlist =
    py{310,311,312,313}-django52-drf{315,316}-ppg2b{286,2910}
    py{39,310,311,312,313}-django42-drf{315,316}-ppg2b{286,2910}
    py{39,310,311,312,313}-django32-drf{315}-ppg2b286

[gh-actions]
# Mapping of Python versions (MAJOR.MINOR) to Tox factors.
# When running Tox inside GitHub Actions, the `tox-gh-actions` plugin automatically:
# 1. Identifies the Python version used to run Tox.
# 2. Determines the corresponding Tox factor for that Python version, based on the `python` mapping below.
# 3. Narrows down the Tox `envlist` to environments that match the factor.
# For more details, please see the `tox-gh-actions` README [0] and architecture documentation [1].
# [0] https://github.com/ymyzk/tox-gh-actions/tree/v2.8.1
# [1] https://github.com/ymyzk/tox-gh-actions/blob/v2.8.1/ARCHITECTURE.md
python =
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313

[testenv]
install_dev_deps = true
allowlist_externals = pytest
deps =
    ppg2b286: psycopg2-binary>=2.8.6
    ppg2b2910: psycopg2-binary>=2.9.10
    drf315: djangorestframework~=3.15.0
    drf316: djangorestframework~=3.16.0
    django32: Django~=3.2.0
    django42: Django~=4.2.0
    django52: Django~=5.2.0

commands =
    pytest {posargs}
