[tox]
isolated_build = True
envlist =
    py39-django32-drf{313,314}
    py310-django32-drf{313,314}

    py39-django40-drf{313,314}
    py310-django40-drf{313,314}

    py39-django41-drf{314}
    py310-django41-drf{314}
    py311-django41-drf{314}

    py39-django42-drf{314,315}
    py310-django42-drf{314,315}
    py311-django42-drf{315}
    py312-django42-drf{315}
    py313-django42-drf{315}

    py310-django50-drf{315}
    py311-django50-drf{315}
    py312-django50-drf{315}
    py313-django50-drf{315}

    py310-django51-drf{315}
    py311-django51-drf{315}
    py312-django51-drf{315}
    py313-django51-drf{315}


[gh-actions]
# Mapping of Python versions (MAJOR.MINOR) to Tox factors.
# When running Tox inside GitHub Actions, the `tox-gh-actions` plugin automatically:
# 1. Identifies the Python version used to run Tox.
# 2. Determines the corresponding Tox factor for that Python version, based on the `python` mapping below.
# 3. Narrows down the Tox `envlist` to environments that match the factor.
# For more details, please see the `tox-gh-actions` README [0] and architecture documentation [1].
# [0] https://github.com/ymyzk/tox-gh-actions/tree/v2.8.1
# [1] https://github.com/ymyzk/tox-gh-actions/blob/v2.8.1/ARCHITECTURE.md
python =
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313

[testenv]
deps =
    django-debug-toolbar>=1.0.0
    factory-boy>=3.2.1
    mixpanel>=4.9.0
    pytest>=2.7
    pytest-django>=3.4
    pytest-mock>=1.10
    psycopg2-binary>=2.8.4
    ruff

    drf313: djangorestframework~=3.13.0
    drf314: djangorestframework~=3.14.0
    drf315: djangorestframework~=3.15.0

    django32: Django~=3.2.0
    django40: Django~=4.0.0
    django41: Django~=4.1.0
    django42: Django~=4.2.0
    django50: Django~=5.0.0
    django51: Django~=5.1.0

commands =
    pytest {posargs}
    ruff check . --fix
