# Generated by Django 3.1.5 on 2021-01-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drf_integrations_example", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="first name"),
        ),
    ]
