name: "Continuous Integration"
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.0
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3

  test:
    needs: lint
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: platform
          POSTGRES_PASSWORD: ""
    env:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]
        django: ["2.2", "3.2"]
      fail-fast: false

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Wait for DB
      run: dockerize -wait tcp://localhost:5432 -timeout 1m
    - name: Build steps
      uses: ./.github/actions/drf-integrations-framework-build
      with:
        python-version: ${{ matrix.python }}
        django-version: ${{ matrix.django }}
    - name: Test with pytest
      run: |
        poetry run pytest --nomigrations
