name: "Continuous Integration"
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.0
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  test:
    needs: lint
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB : postgres
          POSTGRES_USER : postgres
          POSTGRES_PASSWORD : postgres # Password required, can't be blank.
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      PGDATABASE: postgres
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
      fail-fast: false

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - uses: ./.github/actions/drf-integrations-framework-build
      with:
        python-version: ${{ matrix.python-version }}
